modLoader="javafml"
loaderVersion="[34,)"
license="GPLv3"
issueTrackerURL="https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues"

[[mods]]
modId="cfm"
version="7.0.0-pre19"
displayName="MrCrayfish's Furniture Mod"
updateJSONURL="https://raw.githubusercontent.com/MrCrayfish/ModUpdates/master/cfm/update.json"
displayURL="https://mrcrayfish.com/mods?id=cfm"
logoFile="furniture.png"
credits="The people who helped me when I first started creating mods. I wouldn't be here without them!"
authors="MrCrayfish"
description="MrCrayfish's Furniture Mod is all about adding functioning furniture and decorations. This mod currently adds over eighty unique blocks and is continuely growing with new updates."
itemIcon="cfm:stripped_oak_chair"
configBackground="minecraft:textures/block/stripped_oak_log.png"

[[dependencies.cfm]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cfm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,)"
    ordering="NONE"
    side="BOTH"