modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="cfm"
version="7.0.0-pre10"
displayName="MrCrayfish's Furniture Mod"
updateJSONURL="https://raw.githubusercontent.com/MrCrayfish/MrCrayfishFurnitureMod/master/update.json"
displayURL="https://mrcrayfish.com/mods?id=cfm"
logoFile="furniture.png"
credits=""
authors="MrCrayfish"
description="Adds over 80 unique pieces of furniture to the game"

[[dependencies.cfm]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cfm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
[[dependencies.cfm]]
    modId="filters"
    mandatory=false
    versionRange="[1.14.4]"
    ordering="AFTER"
    side="CLIENT"